#!/usr/bin/bash
# generate string constants from the tokens enum (yytokentype from iakab.tab.h),
# to be used in error reporting and what not

# must be run AFTER bison but BEFORE gcc

switchCases=$(cat iakab.tab.h |
grep -Pzo "[^f] enum yytokentype[^}]+" |
sed -E 's/\00/\n/g' |
tail -n +3 |
sed -E 's#/\*(.*)\*/##g' |
sed -E 's/,//g' |
sed -E 's/([A-Za-z_]+) ?= ?(-?[0-9]+)/case \2: return "\1";/'
)

cat > tokens.tab.h <<-END
#ifndef TOKENS_TAB_H_INCLUDED
#define TOKENS_TAB_H_INCLUDED
// AUTOGENERATED

#include "issi.h"
#include "iakab.tab.h"
const char* tokentostr(enum yytokentype);

#endif // TOKENS_TAB_H_INCLUDED
END

cat > tokens.tab.c <<-END
#include <stdlib.h>
#include "tokens.tab.h"
// AUTOGENERATED

const char* tokentostr(enum yytokentype tok) {
    switch (tok) {
END
echo $switchCases >> tokens.tab.c
cat >> tokens.tab.c <<-END
    default: return "[unrecognized token]";
    }
}
END